/*
** EPITECH PROJECT, 2026
** Server.hpp
** File description:
** Server class definition
*/

#ifndef CLIENT
    #define CLIENT

    #include <iostream>
    #include <unistd.h>
    #include "game/Player.hpp"

    #define MAX_BUFFER_SIZE 4096

/**
 * @class Client
 * @brief Stores the server-side state of one connected TCP client.
 *
 * A client owns the socket file descriptor used by the server, the pending
 * read/write buffers, the selected team, the attached player state, and the
 * counters used to enforce the protocol action queue limit.
 */
class Client {
    private:
        int _fd;
        int _playerId;
        std::string _teamName;
        Player _player;

        std::string _readBuffer;
        std::string _writeBuffer;

        int _actionTime;
        int _actionNumber;

        bool _shouldDisconnect;
        bool _incanting;

        /**
         * @brief Parses a protocol player identifier.
         * @param value Textual identifier, optionally prefixed by '#'.
         * @return Parsed numeric identifier.
         */
        int parsePlayerId(std::string value);

    public:
        /**
         * @brief Builds a client bound to an accepted socket.
         * @param fd Connected socket file descriptor.
         */
        Client(int fd);
        ~Client() = default;

        /**
         * @brief Gets the socket file descriptor.
         * @return Client file descriptor.
         */
        int getFd();
        /**
         * @brief Gets the player identifier assigned by the server.
         * @return Player id, or -1 before team registration.
         */
        int getPlayerId() const;
        /**
         * @brief Assigns the player identifier.
         * @param playerId Identifier generated by the server.
         */
        void setPlayerId(int playerId);
        /**
         * @brief Flushes pending bytes from the write buffer to the socket.
         * @throws ClientException when the socket write fails.
         */
        void writeToClient();
        /**
         * @brief Reads available bytes from the socket into the read buffer.
         * @throws ClientException when the peer disconnects or read fails.
         */
        void readFromClient();

        /**
         * @brief Appends data to the pending write buffer.
         * @param str Protocol payload to send later.
         */
        void addBuffer(std::string str);

        /**
         * @brief Gets the mutable write buffer.
         * @return Reference to queued outgoing data.
         */
        std::string& getWriteBuffer();

        /**
         * @brief Gets the mutable read buffer.
         * @return Reference to accumulated incoming data.
         */
        std::string& getReadBuffer();

        /**
         * @brief Gets the cumulative delay of queued actions.
         * @return Delay in milliseconds.
         */
        int getActionTime() const;

        /**
         * @brief Sets the cumulative delay of queued actions.
         * @param newActionTime Delay in milliseconds.
         */
        void setActionTime(int newActionTime);

        /**
         * @brief Gets the number of queued actions.
         * @return Pending action count.
         */
        int getActionNumber() const;

        /**
         * @brief Sets the number of queued actions.
         * @param actionNumber Pending action count.
         */
        void setActionNumber(int actionNumber);

        /**
         * @brief Gets the selected team name.
         * @return Team name, GRAPHIC, or an empty string before registration.
         */
        std::string getTeamName() const;

        /**
         * @brief Assigns the selected team name.
         * @param teamName Team name read from the protocol.
         */
        void setTeamName(std::string &teamName);

        /**
         * @brief Tells whether the client must be disconnected after flushing.
         * @return True when the server should close the connection.
         */
        bool getShouldDisconnect() const;

        /**
         * @brief Marks the client for deferred disconnection.
         * @param shouldDisconnect New disconnection flag.
         */
        void setShouldDisconnect(bool shouldDisconnect);
        /**
         * @brief Tells whether the player is locked in an incantation.
         * @return True while incantation completion is pending.
         */
        bool isIncanting() const;
        /**
         * @brief Updates the incantation lock state.
         * @param incanting New incantation state.
         */
        void setIncanting(bool incanting);

        /**
         * @brief Gets the mutable player state.
         * @return Player attached to the client.
         */
        Player& getPlayer();

        /**
         * @class ClientException
         * @brief Reports socket read and write failures for a client.
         */
        class ClientException : public std::exception {
            public:
                /**
                 * @brief Builds an exception with a diagnostic message.
                 * @param msg Message returned by what().
                 */
                ClientException(const std::string &msg);
                ~ClientException() = default;
                /**
                 * @brief Gets the diagnostic message.
                 * @return Null-terminated message string.
                 */
                const char *what() const noexcept override;

            private:
                std::string _msg;
        };
};

#endif
