"""@file navigation.py
@brief Helpers that translate Zappy vision indexes and broadcast directions into commands.
"""

BROADCAST_MOVES: dict[int, list[str]] = {
    0: [],
    1: ["Forward"],
    2: ["Left", "Forward"],
    3: ["Left", "Forward"],
    4: ["Left", "Forward"],
    5: ["Left", "Left", "Forward"],
    6: ["Right", "Forward"],
    7: ["Right", "Forward"],
    8: ["Right", "Forward"],
}

class Navigation:
    """@brief Computes movement sequences for Zappy's cone-shaped vision grid."""

    def tile_index_to_coords(self, tile_index: int) -> tuple[int, int]:
        """@brief Convert a vision tile index to a row/column coordinate.

        @param tile_index Index returned by the Zappy `Look` command.
        @return `(row, col)` where row is the forward distance and col is lateral offset.
        """
        if tile_index <= 0:
            return (0, 0)
        row : int = 1
        while (row + 1) ** 2 <= tile_index:
            row += 1
        start_of_row : int = row ** 2
        position_in_row : int = tile_index - start_of_row
        col : int = position_in_row - row
        return (row, col)

    def moves_to_tile(self, tile_index: int) -> list[str]:
        """@brief Build the shortest simple command list to reach a visible tile.

        @param tile_index Target tile in the current vision result.
        @return Ordered Zappy movement commands.
        """
        row, col = self.tile_index_to_coords(tile_index)
        moves : list[str] = []
        moves.extend(["Forward"] * row)
        if col < 0:
            moves.append("Left")
            moves.extend(["Forward"] * abs(col))
        elif col > 0:
            moves.append("Right")
            moves.extend(["Forward"] * col)
        return moves

    def move_cost_to_tile(self, tile_index: int) -> int:
        """@brief Estimate movement cost as the number of commands needed.

        @param tile_index Target tile in the current vision result.
        @return Number of commands generated by `moves_to_tile`.
        """
        return len(self.moves_to_tile(tile_index))

    def moves_from_broadcast_direction(self, direction: int) -> list[str]:
        """@brief Convert a broadcast direction into movement commands.

        @param direction Direction id sent by the Zappy server, from 0 to 8.
        @return A new list of commands; unknown directions return an empty list.
        """
        return list(BROADCAST_MOVES.get(direction, []))
